volumes:
  db_data:
secrets:
  root_password:
    file: ./db/root_password.txt
  user_password:
    file: ./db/user_password.txt
networks:
  smart:

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      MARIADB_HOST: db
      MARIADB_DATABASE: smartDB
      MARIADB_PORT: 3306
      MARIADB_USER: donald
      MARIADB_PASSWORD: password
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mariadb:lts
    restart: always
    secrets:
      - root_password
      - user_password
    volumes:
      - db_data:/var/lib/mysql
      - ./db/sqls:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_HOST: localhost
      MARIADB_DATABASE: smartDB
      MARIADB_USER: donald
      MARIADB_PASSWORD_FILE: /run/secrets/user_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/root_password
      TZ: Asia/Singapore
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mariadb-admin", "--protocol", "tcp", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
